use zeroize::Zeroizing;

use super::Caller;

/// Fixed-size application or agent credential, zeroized on drop.
///
/// The type deliberately implements neither `Debug`, `Display`, `Clone`, nor
/// serialization. Possession is authentication evidence, not authorization.
pub struct CallerCredential(Zeroizing<[u8; Self::LENGTH]>);

impl CallerCredential {
    /// Credential size generated by `EnvVault`.
    pub const LENGTH: usize = 32;

    /// Creates credential evidence from an exact issued byte sequence.
    #[must_use]
    pub fn from_bytes(bytes: [u8; Self::LENGTH]) -> Self {
        Self(Zeroizing::new(bytes))
    }

    /// Explicitly exposes credential bytes to a protected transport boundary.
    #[must_use]
    pub fn expose_secret(&self) -> &[u8; Self::LENGTH] {
        &self.0
    }
}

/// Newly registered caller and its one-time credential material.
///
/// This value deliberately implements neither `Debug` nor `Clone`.
pub struct IssuedCallerCredential {
    caller: Caller,
    credential: CallerCredential,
}

impl IssuedCallerCredential {
    pub(crate) const fn new(caller: Caller, credential: CallerCredential) -> Self {
        Self { caller, credential }
    }

    /// Returns the newly registered policy subject.
    #[must_use]
    pub const fn caller(&self) -> Caller {
        self.caller
    }

    /// Returns the credential that must be transported and stored securely.
    #[must_use]
    pub const fn credential(&self) -> &CallerCredential {
        &self.credential
    }

    /// Consumes the issuance result and returns the credential.
    #[must_use]
    pub fn into_credential(self) -> CallerCredential {
        self.credential
    }
}
